server:
  port: 9088
  servlet:
    context-path: /randl2/adminApp
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: prod

jtweb:
  used-fast-json: true