server:
  port: 9088
  servlet:
    context-path: /randl2/adminApp
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: prod

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

