server:
  port: 9087
  servlet:
    context-path: /randl2/user
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    password: 123456
    url: jdbc:p6spy:mysql://localhost:3306/randl2_db?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root

  redis:
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: -1
        min-idle: 0
    password: 123456
    port: 6379
    timeout: 1000

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

security:
  oauth2:
    client:
      client_id: first-client
      client_secret: 12345678
      grant_type: authorization_code
      #授权服务的域名地址不能和客户端的一样，所以分别为127.0.0.1和localhost
      user_authorization_uri: http://localhost:8080/oauth/authorize
      access_token_uri: http://localhost:8080/oauth/token
      #SSO登录地址
      sso_login_url-uri: http://127.0.0.1:8093/authorized


app:
  setting:
    jwt:
      signingKey: ABCD
      issuer: SSD
      validity: 604800000
    admin:
      defaultAppId: 1
      defaultRoleId: 1
    user:
      defaultAppId: 2
      defaultRoleId: 2
