server:
  port: 9086
  servlet:
    context-path: /randl2/resource
  tomcat:
    uri-encoding: UTF-8

spring:
  profiles:
    active: prod

jtweb:
  used-fast-json: true

security:
  oauth2:
    resource:
      filter-order: 3

