server:
  port: 9086
  servlet:
    context-path: /randl2/resource
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    password: 123456
    url: jdbc:p6spy:mysql://localhost:3306/randl2_db?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root

  redis:
    host: 127.0.0.1
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: -1
        min-idle: 0
    password: 123456
    port: 6379
    timeout: 1000

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO

security:
  oauth2:
    resource:
      filter-order: 3
      jwk:
        key-set-uri: http://auth-server:8090/oauth2/keys

app:
  setting:
    jwt:
      signingKey: ABCD
      issuer: SSD
      validity: 604800000
    admin:
      #管理员账号要尽量复杂，不和线上数据库里的账号重复
      account: superadmin
      password: '{noop}superadmin'
      defaultAppId: 1
      defaultRoleId: 1
    user:
      defaultAppId: 2
      defaultRoleId: 2
